services:

  database:
    container_name: database-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: yovpm_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  database-admin:
    container_name: database-admin-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - ${PGADMIN_HOST_PORT}:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: True
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: True
      CONFIG_MAIL_SERVER: mail-server-mailcatcher
      CONFIG_MAIL_PORT: 1025
      CONFIG_MAIL_USE_SSL: False
      CONFIG_MAIL_USE_TLS: False
      CONFIG_MAIL_USERNAME: yovpm-pgadmin@example.com
      CONFIG_MAIL_PASSWORD: random-password

  mail-server:
    container_name: mail-server-mailcatcher
    image: sj26/mailcatcher:latest
    ports:
      - ${MAILCATCHER_HOST_SMTP_PORT}:1025
      - ${MAILCATCHER_WEB_PORT}:1080

volumes:
  db_data:
  pgadmin_data: